title: YoungtakCho Homepage
description: >
  YoungtakCho is a graduate student of [University of Texas at Arlington](https://www.uta.edu).
  Also He is a software developer have more than 3 years experience in various development domains.
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "#"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
