title: YoungtakCho Homepage
description: >
  YOUNGTAK CHO<br>Graduate Student of University of Texas At Arlingtion
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username: "nintyning"
twitter_username: 
linkedin_username: "youngtak-cho-91232396"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "nintyning"
feed_icon: rss
email: "youngtakcho88@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
